name: Stop Fixing CVE-2023-26136
on:
  pull_request:
    paths:
      - 'lib/memstore.js'

jobs:
  no-thank-you:
    name: It's Already Fixed
    runs-on: ubuntu-latest
    steps:
      - env:
          PR: '${{ github.event.number }}'
        run: gh pr close "$PR" --comment "The prototype pollution vulnerability exposed via `MemoryCookieStore` ([CVE-2023-26136](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-26136)) has been patched since [version 4.1.3](https://github.com/salesforce/tough-cookie/releases/v4.1.3). Please upgrade your code to use the latest version of `tough-cookie`."
